steps:
- id: 'run-int-test'
  name: '${_COMPOSER_LOCATION}-docker.pkg.dev/${PROJECT_ID}/airflow-test-container/cicd:latest'
  waitFor: [ '-' ]
  entrypoint: 'bash'
  args:
    - |
      pwd
      ls -l
      ./run_integration_tests.sh $_BASE_BRANCH $SHORT_SHA $_COMPOSER_LOCATION
options:
  dynamic_substitutions: true
substitutions:
  _COMPOSER_LOCATION: europe-west2
  _COMPOSER_ENV: ${PROJECT_ID}
