steps:
- id: 'run-int-test'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: [ '-' ]
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      project_to_branch_map=$(cat ./config/env_mapper.txt)
      for mapping in ${project_to_branch_map[@]}; do
        project_id=$(echo ${mapping} | cut -d":" -f1)
        dag_bucket=$(echo ${mapping} | cut -d":" -f2)
        branch=$(echo ${mapping} | cut -d":" -f3)
        echo "${project_id}--${dag_bucket}--${brach}"
      done
options:
  dynamic_substitutions: true
substitutions:
  _COMPOSER_LOCATION: europe-west2
  _COMPOSER_ENV: ${PROJECT_ID}
