steps:
- id: 'run-int-test'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  waitFor: [ '-' ]
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      pwd
options:
  dynamic_substitutions: true
substitutions:
  _COMPOSER_LOCATION: europe-west2
  _COMPOSER_ENV: ${PROJECT_ID}
