steps:
- id: 'run-int-test'
  name: '${_COMPOSER_LOCATION}-docker.pkg.dev/${PROJECT_ID}/airflow-test-container/cicd:latest'
  waitFor: [ '-' ]
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    pwd && ls -l
options:
  dynamic_substitutions: true
substitutions:
  _COMPOSER_LOCATION: europe-west2
  _COMPOSER_ENV: ${PROJECT_ID}
