steps:
- id: 'run-int-test'
  name: 'gcr.io/$PROJECT_ID/gcloud'
  waitFor: [ 'build-test-container','run-unit-test' ]
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cat /config/env_mapper.txt
options:
  dynamic_substitutions: true
substitutions:
  _COMPOSER_LOCATION: europe-west2
  _COMPOSER_ENV: ${PROJECT_ID}
